exclude:
  - voicebridge-app/server/venv
  - voicebridge-app/server/__pycache__
  - voicebridge-app/server/*.py
  - voicebridge-app/server/*.pkl
  - node_modules
  - .github
  - .gitignore
  - README.md
  - requirements.txt
  - package-lock.json
