name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'voicebridge-app/server/**'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'voicebridge-app/server/**'
      - 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if server runs
      run: |
        cd voicebridge-app/server
        # Run app.py in background
        python app.py &
        # Give it a few seconds to start
        sleep 5
        # Check if server is running on port 5001
        nc -z localhost 5001
        # Kill the server process
        pkill -f "python app.py"

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 voicebridge-app/server --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 voicebridge-app/server --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
