name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Boot Flask server (headless) and ping it
      working-directory: voicebridge-app/server
      env:
        USE_CAMERA: "0"          # ← CI tells app.py *not* to open a webcam
      run: |
        # launch server in background, no auto-reload
        python app.py &          # relies on app.run(use_reloader=False) in your patch
        SERVER_PID=$!
        # give it a moment to bind
        sleep 5
        # verify port 5001 is listening
        nc -z 127.0.0.1 5001
        # cleanly stop the server
        kill $SERVER_PID

    #- name: Lint with flake8
    #  run: |
    #    pip install flake8
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 voicebridge-app/server --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings
    #    flake8 voicebridge-app/server --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
