name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:  # Job for front-end (React app) checks
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'  # Cache npm modules based on lock file&#8203;:contentReference[oaicite:13]{index=13}

      - name: Install dependencies (Frontend)
        run: npm ci
        working-directory: voicebridge-app/client

      - name: Lint (ESLint)
        run: npm run lint
        working-directory: voicebridge-app/client

      - name: Build (Vite)
        run: npm run build
        working-directory: voicebridge-app/client

      # (Optional) - name: Run frontend tests
      # run: npm test
      # working-directory: voicebridge-app/client

  backend:  # Job for back-end (Python API & ML) checks
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # Cache pip downloads&#8203;:contentReference[oaicite:14]{index=14}

      - name: Install dependencies (Backend)
        run: pip install -r requirements.txt

      - name: Lint (Flake8)
        run: |
          pip install flake8
          flake8 .
        working-directory: .  # Lint all Python files in the repo

      - name: Run backend tests
        run: pytest
        # If tests exist, ensure any test requirements are installed (e.g., pytest)
